### ISSUE TITLE
乱码问题求助

### ISSUE THREAD

**Issue by imkerberos** [IceEnd/1chat#13]
感谢作者写了这么好的软件.
在使用自定义的 host proxy 的时候, 出现乱码, 问题大约是什么原因?
对 VUE 和 js 生态不熟悉, 请给点提示.
<img width="486" alt="image" src="https://github.com/IceEnd/1chat/assets/636187/df8c8d16-1fbf-4de9-ae00-70c43939634e">

**Comment by IceEnd** [comment]
看着像是生成为文本不是 utf-8 编吗的。可以把文本贴出来看看

**Comment by imkerberos** [comment]
找到原因了，不是源文本的问题。是上游一个 textdecoder 流式解码的 bug。我看很多 gpt 客户端都用了这个，问题是一样的，不过我没有能力修改。
